---
version: "3"

services:
  bgw320-influx:
    image: ghcr.io/sholiday/bgw320-influx:latest
    restart: unless-stopped
    environment:
      - BGW320_ROUTERIP=192.168.1.254
      - BGW320_INFLUXHOST=host
      - BGW320_INFLUXPORT=port
      - BGW320_INFLUXUSER=user
      - BGW320_INFLUXPASS=pass
